/* Generated By:JavaCC: Do not edit this line. PL40603Constants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface PL40603Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PLUS = 7;
  /** RegularExpression Id. */
  int MINUS = 8;
  /** RegularExpression Id. */
  int MULTIPLY = 9;
  /** RegularExpression Id. */
  int DIVIDE = 10;
  /** RegularExpression Id. */
  int lbrace = 11;
  /** RegularExpression Id. */
  int rbrace = 12;
  /** RegularExpression Id. */
  int lparen = 13;
  /** RegularExpression Id. */
  int rparen = 14;
  /** RegularExpression Id. */
  int DIGIT = 15;
  /** RegularExpression Id. */
  int LETTER = 16;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "<DIGIT>",
    "<LETTER>",
    "\"main\"",
    "\",\"",
    "\";\"",
    "\"while\"",
    "\"for\"",
    "\"=\"",
    "\"if\"",
    "\"else\"",
    "\"break\"",
    "\"continue\"",
    "\"return\"",
    "\"?\"",
    "\":\"",
    "\"|\"",
    "\"&\"",
    "\"==\"",
    "\"!\"",
    "\">\"",
    "\"<\"",
    "\"<=\"",
    "\">=\"",
    "\"%\"",
  };

}
